name: Release

on:
  push:
    branches: [master, next]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure git author
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      run: |
        npm i -g pnpm
        pnpm i --frozen-lockfile
    - name: Lint
      run: pnpm run lint
    - name: Test
      run: pnpm run -r test
    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
        npm whoami
        npx lerna publish --yes
